# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='scope',
            field=models.CharField(default=b'users category task tag read write', max_length=255, verbose_name=b'scope'),
        ),
    ]
