# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='creator',
            field=models.DateField(default=datetime.datetime(2016, 2, 4, 12, 2, 2, 23945), max_length=255, verbose_name=b'creator'),
        ),
    ]
