# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='creator',
            field=models.DateField(default=django.utils.timezone.now, max_length=255, verbose_name=b'creator'),
        ),
    ]
