# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_added'),
        ),
        migrations.AddField(
            model_name='category',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_modified'),
        ),
    ]
