# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20160204_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.IntegerField(default=0, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name='parent_id'),
        ),
    ]
