# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20160204_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='owner',
            field=models.CharField(default='', max_length=255, verbose_name='owner'),
        ),
    ]
